In [16]:
import pandas as pd

In [17]:
df_clustered_2018 = pd.read_csv('clustered_data.csv')
df_clustered_2018

,Country Name,Renewable energy consumption (% of total final energy consumption) - EG.FEC.RNEW.ZS,"Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes",Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS,Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS,Cluster
0,Angola,56.785500,37.679,1.440151,22.406890,4
1,Albania,38.266399,5.403,1.244828,1.007232,0
2,United Arab Emirates,0.259200,188.541,2.035783,5.148113,0
3,Argentina,10.520800,185.030,1.572326,1.659070,0
4,Armenia,11.133000,6.297,1.754916,0.504952,0
...,...,...,...,...,...,...
157,Vietnam,23.491800,211.774,3.784400,1.345750,2
158,Vanuatu,30.777000,0.145,0.695169,0.000000,0
159,South Africa,10.343300,472.001,5.115334,1.693617,2
160,Zambia,85.104599,6.930,0.923608,4.339297,3
161,Zimbabwe,81.363602,11.341,2.003068,2.085152,3

In [18]:
df_raw = pd.read_csv('WorldSustainabilityDataset.csv')
df_raw

,Country Name,Country Code,Year,Access to electricity (% of population) - EG.ELC.ACCS.ZS,Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG,"Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS",Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS,Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS,Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS,Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS,...,Gini index (World Bank estimate) - SI.POV.GINI,Income Classification (World Bank Definition),Individuals using the Internet (% of population) - IT.NET.USER.ZS,"Life expectancy at birth, total (years) - SP.DYN.LE00.IN","Population, total - SP.POP.TOTL",Regime Type (RoW Measure Definition),Rural population (% of total population) - SP.RUR.TOTL.ZS,Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS,Urban population (% of total population) - SP.URB.TOTL.IN.ZS,World Regions (UN SDG Definition)
0,Aruba,ABW,2000,91.660398,NaN,15.392211,2.389134,0.000190,0.000190,NaN,...,NaN,High income,NaN,NaN,NaN,NaN,53.283,NaN,NaN,Latin America and Caribbean
1,Aruba,ABW,2001,100.000000,NaN,11.491930,2.509046,0.000214,0.000214,NaN,...,NaN,High income,17.100000,73.853,92892.0,NaN,53.661,0.000712,46.339,Latin America and Caribbean
2,Aruba,ABW,2002,100.000000,NaN,3.893620,2.721385,0.000223,0.000223,NaN,...,NaN,High income,18.800000,73.937,94992.0,NaN,54.028,0.000657,45.972,Latin America and Caribbean
3,Aruba,ABW,2003,100.000000,NaN,6.713863,2.733676,0.000243,0.000243,NaN,...,NaN,High income,20.800000,74.038,97016.0,NaN,54.394,0.000700,45.606,Latin America and Caribbean
4,Aruba,ABW,2004,100.000000,NaN,9.801576,2.678363,0.000256,0.000256,NaN,...,NaN,High income,23.000000,74.156,98744.0,NaN,54.760,0.000685,45.240,Latin America and Caribbean
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3282,Zimbabwe,ZWE,2014,32.300000,0.763955,-14.094023,2.310859,1.573499,0.000000,1.426705,...,NaN,Low income,16.364740,58.410,13586710.0,Electoral Autocracy,67.496,5.531514,32.504,Sub-Saharan Africa
3283,Zimbabwe,ZWE,2015,33.700000,10.749009,-18.882831,2.381654,0.844003,0.000000,1.492774,...,NaN,Low income,22.742818,59.534,13814642.0,Electoral Autocracy,67.615,4.561981,32.385,Sub-Saharan Africa
3284,Zimbabwe,ZWE,2016,39.676228,-0.716048,-11.199213,2.101249,0.823740,0.000000,1.496494,...,NaN,Low income,23.119989,60.294,14030338.0,Electoral Autocracy,67.704,4.473632,32.296,Sub-Saharan Africa
3285,Zimbabwe,ZWE,2017,40.144283,28.172572,-12.700238,2.102515,1.300127,0.000000,1.422511,...,44.3,Low income,24.400000,60.812,14236599.0,Electoral Autocracy,67.763,4.844665,32.237,Sub-Saharan Africa
3286,Zimbabwe,ZWE,2018,40.616360,61.556580,NaN,2.003068,2.085152,0.000000,1.422511,...,NaN,Low income,25.000000,61.195,14438812.0,Electoral Autocracy,67.791,4.363782,32.209,Sub-Saharan Africa

In [19]:
cluster_mapping = df_clustered_2018[['Country Name', 'Cluster']]
countries_in_analysis = cluster_mapping['Country Name'].unique()
print(f"Successfully extracted {len(countries_in_analysis)} countries.")

Successfully extracted 162 countries.

In [20]:
# keep only the countries which is in our clustered data
df_historical = df_raw[df_raw['Country Name'].isin(countries_in_analysis)].copy()
print(f"The filtered historical dataset contains a total of {df_historical.shape[0]} records.")

The filtered historical dataset contains a total of 3078 records.

In [28]:
df_final = pd.merge(df_historical, cluster_mapping, on='Country Name', how='left')
print("Preview of the columns in the final merged dataset", df_final.columns.tolist())

Preview of the columns in the final merged dataset ['Country Name', 'Country Code', 'Year', 'Access to electricity (% of population) - EG.ELC.ACCS.ZS', 'Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG', 'Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS', 'Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS', 'Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS', 'Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS', 'Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS', 'Automated teller machines (ATMs) (per 100,000 adults) - FB.ATM.TOTL.P5', 'Broad money (% of GDP) - FM.LBL.BMNY.GD.ZS', 'Children out of school (% of primary school age) - SE.PRM.UNER.ZS', 'Compulsory education, duration (years) - SE.COM.DURS', 'Cost of business start-up procedures, female (% of GNI per capita) - IC.REG.COST.PC.FE.ZS', 'Cost of business start-up procedures, male (% of GNI per capita) - IC.REG.COST.PC.MA.ZS', 'Exports of goods and services (% of GDP) - NE.EXP.GNFS.ZS', 'Final consumption expenditure (% of GDP) - NE.CON.TOTL.ZS', 'GDP (current US$) - NY.GDP.MKTP.CD', 'GDP per capita (current US$) - NY.GDP.PCAP.CD', 'General government final consumption expenditure (% of GDP) - NE.CON.GOVT.ZS', 'Gross national expenditure (% of GDP) - NE.DAB.TOTL.ZS', 'Gross savings (% of GDP) - NY.GNS.ICTR.ZS', 'Imports of goods and services (% of GDP) - NE.IMP.GNFS.ZS', 'Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG', 'Primary completion rate, total (% of relevant age group) - SE.PRM.CMPT.ZS', 'Proportion of seats held by women in national parliaments (%) - SG.GEN.PARL.ZS', 'Pupil-teacher ratio, primary - SE.PRM.ENRL.TC.ZS', 'Renewable electricity output (% of total electricity output) - EG.ELC.RNEW.ZS', 'Renewable energy consumption (% of total final energy consumption) - EG.FEC.RNEW.ZS', 'School enrollment, preprimary (% gross) - SE.PRE.ENRR', 'School enrollment, primary (% gross) - SE.PRM.ENRR', 'School enrollment, secondary (% gross) - SE.SEC.ENRR', 'Trade (% of GDP) - NE.TRD.GNFS.ZS', 'Women Business and the Law Index Score (scale 1-100) - SG.LAW.INDX', 'Prevalence of undernourishment (%) - SN_ITK_DEFC - 2.1.1', 'Proportion of population below international poverty line (%) - SI_POV_DAY1 - 1.1.1', 'Proportion of population covered by at least a 2G mobile network (%) - IT_MOB_2GNTWK - 9.c.1', 'Proportion of population covered by at least a 3G mobile network (%) - IT_MOB_3GNTWK - 9.c.1', 'Proportion of population using basic drinking water services (%) - SP_ACS_BSRVH2O - 1.4.1', 'Unemployment rate, male (%) - SL_TLF_UEM - 8.5.2', 'Unemployment rate, women (%) - SL_TLF_UEM - 8.5.2', 'Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes', 'Continent', 'Gini index (World Bank estimate) - SI.POV.GINI', 'Income Classification (World Bank Definition)', 'Individuals using the Internet (% of population) - IT.NET.USER.ZS', 'Life expectancy at birth, total (years) - SP.DYN.LE00.IN', 'Population, total - SP.POP.TOTL', 'Regime Type (RoW Measure Definition)', 'Rural population (% of total population) - SP.RUR.TOTL.ZS', 'Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS', 'Urban population (% of total population) - SP.URB.TOTL.IN.ZS', 'World Regions (UN SDG Definition)', 'Cluster']

Test wether it successfully merge or not

In [44]:
if 'Cluster' in df_final.columns:
    print("The 'Cluster' column has been successfully added.")
    
    # check if any rows have an NaN value in the 'Cluster' column
    if df_final['Cluster'].isnull().any():
        print("Warning: Empty Cluster values were found after merging. Please check the data.")
    else:
        print("All historical records have been successfully labelled with their respective clusters.")
else:
    print("Error: The 'Cluster' column does not exist after merging. Please check the merge logic.")

The 'Cluster' column has been successfully added.
All historical records have been successfully labelled with their respective clusters.

In [33]:
import os

In [46]:
output = 'final_cluster_datasets'
if not os.path.exists(output):
    os.makedirs(output)

clusters = df_final['Cluster'].dropna().unique() # Remove any NaN values that may have resulted from the merge.
clusters.sort()

for i in clusters:
    df_cluster = df_final[df_final['Cluster'] == i]
    
    output_filename = os.path.join(output, f'cluster_{int(i)}_data.csv')

    df_cluster.to_csv(output_filename, index=False)
    
    print(f"Successfully exported the data for Cluster {int(i)}")
    print(f"Including {df_cluster['Country Name'].nunique()} countries")
    print(f"The file save as {output_filename}")

Successfully exported the data for Cluster 0
Including 87 countries
The file save as final_cluster_datasets/cluster_0_data.csv
Successfully exported the data for Cluster 1
Including 2 countries
The file save as final_cluster_datasets/cluster_1_data.csv
Successfully exported the data for Cluster 2
Including 21 countries
The file save as final_cluster_datasets/cluster_2_data.csv
Successfully exported the data for Cluster 3
Including 44 countries
The file save as final_cluster_datasets/cluster_3_data.csv
Successfully exported the data for Cluster 4
Including 8 countries
The file save as final_cluster_datasets/cluster_4_data.csv